Can not use Guava versions greater than 20. Guava has some big changes since version 21, NoSuchMethodError appears if you are using version 21 or later. The Guava version that is dependent on Solr7's pom.xml is 14, and the Guava version that is dependent on tika-parsers is version 17.