Excluded some Jetty components that conflicted with container-level libraries when running in Jetty.
These Jetty components were pulled in as transitive dependencies of Solr, and could cause NoClassDefFoundErrors under some circumstances, e.g. when exceptions were logged during startup.